# Generated by Django 5.0.6 on 2025-09-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(default='GPT', max_length=50)),
                ('phase', models.CharField(default='Phase3', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('dataset_path', models.CharField(blank=True, max_length=500)),
                ('current_epoch', models.IntegerField(default=0)),
                ('total_epochs', models.IntegerField(default=10)),
                ('current_cycle', models.IntegerField(default=0)),
                ('total_cycles', models.IntegerField(default=1)),
                ('current_loss', models.FloatField(blank=True, null=True)),
                ('best_loss', models.FloatField(blank=True, null=True)),
                ('perplexity', models.FloatField(blank=True, null=True)),
                ('gpu_name', models.CharField(blank=True, max_length=200)),
                ('gpu_memory_used', models.FloatField(blank=True, null=True)),
                ('claude_enabled', models.BooleanField(default=False)),
                ('claude_suggestions', models.JSONField(default=list)),
                ('claude_cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('process_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('cycle', models.IntegerField(default=1)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('train_loss', models.FloatField()),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('perplexity', models.FloatField(blank=True, null=True)),
                ('learning_rate', models.FloatField(blank=True, null=True)),
                ('gpu_memory_used', models.FloatField(blank=True, null=True)),
                ('gpu_utilization', models.FloatField(blank=True, null=True)),
                ('gpu_temperature', models.FloatField(blank=True, null=True)),
                ('epoch_time', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.trainingsession')),
            ],
            options={
                'ordering': ['session', 'cycle', 'epoch', 'batch'],
            },
        ),
    ]
